interface Coach {
    id: number;
    name: string;
    specialization: string;
    bio: string;
    image: string;
    age: number;
    experience: string;
    certifications: string[];
    contact: string;
  }

export const coaches: Coach[] = [
    {
      id: 0,
      name: "Ian Clyde Tejada",
      specialization: "Strength and Conditioning Coach",
      bio: "Ian focuses on improving physical performance and injury prevention.",
      image: "/pictures/Clyde.png",
      age: 31,
      experience: "9 years",
      certifications: ["CSCS", "First Aid Certified"],
      contact: "ian.tejada@example.com",
    },
    {
      id: 1,
      name: "Emily Johnson",
      specialization: "Nutritionist",
      bio: "Emily helps clients achieve their dietary goals effectively.",
      image: "https://via.placeholder.com/150",
      age: 32,
      experience: "8 years",
      certifications: ["Registered Dietitian", "Sports Nutrition Specialist"],
      contact: "emily.johnson@example.com",
    },
    {
      id: 2,
      name: "Rhea Rizz Perocho",
      specialization: "Pilates Instructor",
      bio: "Rhea helps individuals achieve strength and flexibility through Pilates.",
      image: "/pictures/Rhea.jpg",
      age: 29,
      experience: "7 years",
      certifications: ["Certified Pilates Instructor"],
      contact: "rhea.perocho@example.com",
    },
    {
      id: 3,
      name: "Jane Smith",
      specialization: "Yoga Instructor",
      bio: "Jane specializes in Hatha and Vinyasa yoga techniques.",
      image: "https://via.placeholder.com/150",
      age: 28,
      experience: "6 years",
      certifications: ["RYT 500", "Meditation Teacher"],
      contact: "jane.smith@example.com",
    },
    {
      id: 4,
      name: "Chito Miguel Poral",
      specialization: "Martial Arts Instructor",
      bio: "Chito trains individuals in self-defense and mixed martial arts.",
      image: "/pictures/Chito.jpg",
      age: 34,
      experience: "10 years",
      certifications: ["Black Belt in Karate", "MMA Trainer"],
      contact: "chito.poral@example.com",
    },
    {
      id: 5,
      name: "Allan Loyd Pacete",
      specialization: "Boxing Trainer",
      bio: "Allan trains clients in professional and fitness-oriented boxing.",
      image: "/pictures/Allan.jpg",
      age: 36,
      experience: "12 years",
      certifications: ["Professional Boxing Trainer"],
      contact: "allan.pacete@example.com",
    },
    {
      id: 6,
      name: "John Patrick Pineda",
      specialization: "Swimming Coach",
      bio: "John specializes in competitive and recreational swimming techniques.",
      image: "/pictures/Patrick.jpg",
      age: 30,
      experience: "8 years",
      certifications: ["Certified Swim Coach", "Lifeguard Certified"],
      contact: "john.pineda@example.com",
    },
    {
      id: 7,
      name: "John Doe",
      specialization: "Fitness Trainer",
      bio: "John is a certified fitness trainer with 10 years of experience.",
      image: "https://via.placeholder.com/150",
      age: 35,
      experience: "10 years",
      certifications: ["Certified Personal Trainer", "CPR Certified"],
      contact: "john.doe@example.com",
    },
    {
      id: 8,
      name: "Lois Kirsten Alonsagay",
      specialization: "Dance Instructor",
      bio: "Lois teaches contemporary and ballroom dance techniques.",
      image: "/pictures/Lois.jpg",
      age: 27,
      experience: "5 years",
      certifications: ["Certified Dance Coach"],
      contact: "lois.alonsagay@example.com",
    },
    {
      id: 9,
      name: "Manaf Kassim",
      specialization: "Calisthenics Coach",
      bio: "Manaf helps clients achieve strength and mobility using bodyweight exercises.",
      image: "/pictures/Manaf.jpg",
      age: 33,
      experience: "7 years",
      certifications: ["Certified Calisthenics Trainer", "CPR Certified"],
      contact: "manaf.kassim@example.com",
    },
    {
      id: 10,
      name: "Sheree Laluma",
      specialization: "Zumba Instructor",
      bio: "Sheree brings energy and fun to fitness with her Zumba sessions.",
      image: "/pictures/Sheree.jpg",
      age: 29,
      experience: "6 years",
      certifications: ["Zumba Certified Instructor"],
      contact: "sheree.laluma@example.com",
    },
  ];