interface Customer {
  uid: string;
  firstName: string;
  lastName: string;
  email: string;
  sex: string;
  dob: string;
  status: string;
  requestNumber: string;
  timeApproved: string;
  subscription: string;
  remainingTime: string;
  isActive: boolean;
}

export const customers: Customer[] = [
  {
    uid: "001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    sex: "Male",
    dob: "1990-05-14",
    status: "New Customer",
    requestNumber: "0000005",
    timeApproved: "30 minutes ago",
    subscription: "Premium",
    remainingTime: "30 days",
    isActive: true,
  },
  {
    uid: "002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    sex: "Female",
    dob: "1985-08-22",
    status: "Signed Up",
    requestNumber: "0000002",
    timeApproved: "2 hours ago",
    subscription: "Basic",
    remainingTime: "2 weeks",
    isActive: false,
  },
  {
    uid: "003",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    sex: "Female",
    dob: "1992-11-05",
    status: "Content",
    requestNumber: "0000003",
    timeApproved: "1 day ago",
    subscription: "Standard",
    remainingTime: "20 days",
    isActive: true,
  },
  {
    uid: "004",
    firstName: "Bob",
    lastName: "Brown",
    email: "bob.brown@example.com",
    sex: "Male",
    dob: "1988-04-17",
    status: "New Customer",
    requestNumber: "0000006",
    timeApproved: "3 days ago",
    subscription: "Premium",
    remainingTime: "1 month",
    isActive: false,
  },
  {
    uid: "005",
    firstName: "Charlie",
    lastName: "Davis",
    email: "charlie.davis@example.com",
    sex: "Male",
    dob: "1995-07-19",
    status: "Signed Up",
    requestNumber: "0000004",
    timeApproved: "5 hours ago",
    subscription: "Basic",
    remainingTime: "25 days",
    isActive: true,
  },
  {
    uid: "006",
    firstName: "Emily",
    lastName: "Wilson",
    email: "emily.wilson@example.com",
    sex: "Female",
    dob: "1989-06-25",
    status: "Content",
    requestNumber: "0000001",
    timeApproved: "1 week ago",
    subscription: "Standard",
    remainingTime: "18 days",
    isActive: false,
  },
  {
    uid: "007",
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    sex: "Male",
    dob: "1993-09-30",
    status: "New Customer",
    requestNumber: "0000007",
    timeApproved: "2 days ago",
    subscription: "Premium",
    remainingTime: "40 days",
    isActive: true,
  },
  {
    uid: "008",
    firstName: "Sophia",
    lastName: "Garcia",
    email: "sophia.garcia@example.com",
    sex: "Female",
    dob: "1991-12-12",
    status: "Signed Up",
    requestNumber: "0000002",
    timeApproved: "4 days ago",
    subscription: "Basic",
    remainingTime: "2 weeks",
    isActive: false,
  },
  {
    uid: "009",
    firstName: "Ethan",
    lastName: "Lee",
    email: "ethan.lee@example.com",
    sex: "Male",
    dob: "1997-03-08",
    status: "Content",
    requestNumber: "0000003",
    timeApproved: "6 hours ago",
    subscription: "Standard",
    remainingTime: "22 days",
    isActive: true,
  },
  {
    uid: "010",
    firstName: "Olivia",
    lastName: "Harris",
    email: "olivia.harris@example.com",
    sex: "Female",
    dob: "1994-10-27",
    status: "New Customer",
    requestNumber: "0000004",
    timeApproved: "3 weeks ago",
    subscription: "Premium",
    remainingTime: "28 days",
    isActive: false,
  },
];
