name: Cleanup Jest Files

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  delete-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete __test__ folder and Jest files
        run: |
          echo "Deleting __test__ directory and Jest configuration files..."
          rm -rf __test__ jest.config.ts jest.setup.js jest.setup.ts
          
      - name: create pull request
        run: 
          gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
