name: Cleanup Jest Files

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  delete-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete __test__ folder and Jest files
        run: |
          echo "Deleting __test__ directory and Jest configuration files..."
          rm -rf __test__ jest.config.ts jest.setup.js jest.setup.ts
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: delete test files
          title: Delete Test Files
          body: run by actions
          branch: cleanup-branch
