name: Cleanup Jest Files

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  delete-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete __test__ folder and Jest files
        run: |
          echo "Deleting __test__ directory and Jest configuration files..."
          rm -rf __test__ jest.config.ts jest.setup.js jest.setup.ts # Add any additional Jest files here
          
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Cleanup: Remove __test__ and Jest files"
          body: "This PR removes the __test__ directory and Jest configuration files."
          base: staging
          branch: cleanup-jest-files
          path: .
