name: Cleanup Jest Files

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write
jobs:
  delete-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete __test__ folder and Jest files
        run: |
          echo "Deleting __test__ directory and Jest configuration files..."
          rm -rf __test__ jest.config.ts jest.setup.js jest.setup.ts
          
      - name: create pull request
        run: 
          gh pr create -B main -H staging --title 'Merge staging into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}