
name: Run Testing

on:
  pull_request:
    branches:
      - testing
jobs:
  Run-Test:
    name: Run Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: npm run test -- -u